inherit_from:
 - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'
Metrics/LineLength:
  Max: 140